# --- Window & Layout ---
hide_window_decorations titlebar-only
remember_window_size    no
initial_window_width    80c
initial_window_height   25c
window_padding_width    16
placement_strategy      center

# --- Fonts & Spacing ---
font_family             Maple Mono NF
font_size               12.0
modify_font cell_height +8px

# --- Clean Fade Tab Bar ---
tab_bar_edge            bottom
tab_bar_style           fade
tab_fade                0.75 1.0
tab_bar_min_tabs        2
tab_title_template      " {index} • {title} "
active_tab_font_style   bold

# --- Misc ---
copy_on_select          yes

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
