# --- Window & Layout ---
hide_window_decorations yes
remember_window_size    no
initial_window_width    80c
initial_window_height   30c
window_padding_width    12
placement_strategy      center

# --- Fonts & Spacing ---
font_family             Maple Mono NF
font_size               12.0
modify_font cell_height 120%

# --- Clean Fade Tab Bar ---
tab_bar_edge            bottom
tab_bar_style           fade
tab_fade                0.75 1.0
tab_bar_min_tabs        2
tab_title_template      " {index} • {title} "
active_tab_font_style   bold

# --- Transparency ---
background_opacity      0.95

# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
